module.exports = {
  apps: [
    {
      name: "whatsapp-watcher",
      script: "whatsapp_playwright_watcher.py",
      interpreter: "D:\\AI_Employee_Vault\\.venv\\Scripts\\pythonw.exe",
      cwd: "D:/AI_Employee_Vault",
      watch: false,
      autorestart: true,
      restart_delay: 10000,
      max_restarts: 10,
      log_file: "D:/AI_Employee_Vault/Logs/whatsapp_watcher.log",
      error_file: "D:/AI_Employee_Vault/Logs/whatsapp_watcher_error.log",
      time: true,
    },
    {
      name: "file-watcher",
      script: "watcher.py",
      interpreter: "D:\\AI_Employee_Vault\\.venv\\Scripts\\pythonw.exe",
      cwd: "D:/AI_Employee_Vault",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      log_file: "D:/AI_Employee_Vault/Logs/file_watcher.log",
      error_file: "D:/AI_Employee_Vault/Logs/file_watcher_error.log",
      time: true,
    },
    {
      name: "odoo-mcp",
      script: "MCP/odoo_mcp.js",
      interpreter: "node",
      cwd: "D:/AI_Employee_Vault",
      watch: false,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 10,
      env: {
        ODOO_MOCK: "true",
        MCP_PORT: "3000",
      },
      log_file: "D:/AI_Employee_Vault/Logs/odoo_mcp.log",
      error_file: "D:/AI_Employee_Vault/Logs/odoo_mcp_error.log",
      time: true,
    },
  ]
};
