"""
AI Employee Vault — Recurring Task Scheduler (Silver Tier)
Reads cron schedules from config.yaml and creates tasks when due.
Stores last-run timestamps in scheduler_state.json.
"""

import json
from datetime import datetime
from pathlib import Path

from croniter import croniter
from config_loader import load_config, get_path, log_event

VAULT_PATH = Path(__file__).parent.resolve()
STATE_FILE = VAULT_PATH / "scheduler_state.json"


def load_state() -> dict:
    """Load scheduler state (last run times per job)."""
    if STATE_FILE.exists():
        with STATE_FILE.open("r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_state(state: dict) -> None:
    """Persist scheduler state to disk."""
    with STATE_FILE.open("w", encoding="utf-8") as f:
        json.dump(state, f, indent=2)


def is_due(cron_expr: str, last_run: str | None, now: datetime) -> bool:
    """Check if a cron job is due based on its expression and last run time."""
    if last_run is None:
        # Never run before — check if cron time has passed today
        cron = croniter(cron_expr, now.replace(hour=0, minute=0, second=0))
        next_time = cron.get_next(datetime)
        return next_time <= now
    last_dt = datetime.fromisoformat(last_run)
    cron = croniter(cron_expr, last_dt)
    next_time = cron.get_next(datetime)
    return next_time <= now


def create_scheduled_task(name: str, template: str, priority: str) -> Path:
    """Create a task file in /Needs_Action from a scheduler template."""
    inbox = get_path("inbox")
    inbox.mkdir(parents=True, exist_ok=True)
    now = datetime.now()
    filename = f"{name}_{now.strftime('%Y%m%d')}.md"
    filepath = inbox / filename

    lines = [
        "---",
        f"type: scheduled_task",
        f"priority: {priority}",
        f"source: scheduler",
        f"created: {now.strftime('%Y-%m-%d %H:%M')}",
        f"sla_deadline: auto",
        "---",
        "",
        f"# {name.replace('_', ' ').title()}",
        "",
        template,
        "",
        f"*Auto-generated by scheduler at {now.strftime('%H:%M')}*",
    ]
    filepath.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return filepath


def check_due_tasks(now: datetime | None = None) -> list[str]:
    """Check all scheduled tasks and create any that are due. Returns list of created task names."""
    now = now or datetime.now()
    cfg = load_config()
    schedules = cfg.get("scheduler", [])
    state = load_state()
    created = []

    for job in schedules:
        name = job["name"]
        cron_expr = job["cron"]
        template = job["template"]
        priority = job.get("priority", cfg.get("priority", {}).get("default", "P2"))
        last_run = state.get(name)

        if is_due(cron_expr, last_run, now):
            filepath = create_scheduled_task(name, template, priority)
            state[name] = now.isoformat()
            created.append(name)
            log_event("Scheduled Task Created", [
                f"Job: {name}",
                f"Priority: {priority}",
                f"File: {filepath.name}",
            ])

    save_state(state)
    return created


if __name__ == "__main__":
    print("Checking scheduled tasks...")
    created = check_due_tasks()
    if created:
        print(f"Created tasks: {', '.join(created)}")
    else:
        print("No tasks due at this time.")
