"""
Weekly Briefing Script — Gold/Platinum Tier
Reads Accounting/transactions.csv → generates CEO_Briefing.md + Reports/weekly_YYYYMMDD.md
"""
import csv
from pathlib import Path
from datetime import datetime, timedelta

VAULT = Path(__file__).resolve().parent.parent
REPORTS = VAULT / "Reports"
REPORTS.mkdir(exist_ok=True)
ACCOUNTING = VAULT / "Accounting"
CSV_PATH = ACCOUNTING / "transactions.csv"
CEO_BRIEF = VAULT / "CEO_Briefing.md"
LOG_PATH = VAULT / "Logs" / f"{datetime.now().strftime('%Y-%m-%d')}.md"


def read_transactions():
    if not CSV_PATH.exists():
        return []
    with CSV_PATH.open("r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main():
    rows = read_transactions()
    now = datetime.now()
    last_week = now - timedelta(days=7)

    weekly = []
    for r in rows:
        try:
            d = datetime.fromisoformat(r.get("date", "").strip())
            if d >= last_week:
                weekly.append(r)
        except Exception:
            continue

    revenue = sum(float(r.get("credit", "0") or 0) for r in weekly)
    expenses = sum(float(r.get("debit", "0") or 0) for r in weekly)
    net = revenue - expenses

    # Pending approvals count
    pending = len(list((VAULT / "Pending_Approval").glob("*.md")))
    done_count = len(list((VAULT / "Done").glob("*.md")))

    report = f"""---
type: ceo_briefing
generated: {now.strftime('%Y-%m-%d %H:%M')}
period: {(now - timedelta(days=7)).strftime('%Y-%m-%d')} to {now.strftime('%Y-%m-%d')}
tier: platinum
---

# CEO Briefing — {now.strftime('%A, %d %B %Y')}

## Financial Summary (Last 7 Days)

| Metric | Amount |
|--------|--------|
| Revenue | Rs. {revenue:,.0f} |
| Expenses | Rs. {expenses:,.0f} |
| **Net** | **Rs. {net:,.0f}** |

## Operational Status

| KPI | Value |
|-----|-------|
| Tasks Completed | {done_count} |
| Pending Approvals | {pending} |
| Bottlenecks | {'Review {pending} pending approvals' if pending else 'None — all clear'} |

## Risk Flags
{'- ⚠️ ' + str(pending) + ' items awaiting human approval' if pending else '- ✅ No pending approvals'}

## Transactions This Week
| Date | Credit | Debit | Description |
|------|--------|-------|-------------|
{''.join(f"| {r.get('date','')[:10]} | Rs. {float(r.get('credit','0') or 0):,.0f} | Rs. {float(r.get('debit','0') or 0):,.0f} | {r.get('description','')} |" + chr(10) for r in weekly)}
## Next Actions
1. Review and approve items in /Pending_Approval/
2. Follow up on outstanding invoices
3. Schedule weekly sync with team

*Generated by AI Employee (Platinum Tier) — {now.strftime('%Y-%m-%d %H:%M')}*
"""

    CEO_BRIEF.write_text(report, encoding="utf-8")
    report_file = REPORTS / f"weekly_{now.strftime('%Y%m%d')}.md"
    report_file.write_text(report, encoding="utf-8")

    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with LOG_PATH.open("a", encoding="utf-8") as log:
        log.write(
            f"\n## {now.strftime('%H:%M')} - Weekly Briefing Generated\n"
            f"- Revenue: Rs. {revenue:,.0f}\n"
            f"- Expenses: Rs. {expenses:,.0f}\n"
            f"- Net: Rs. {net:,.0f}\n"
            f"- Pending approvals: {pending}\n"
            f"- Saved: {CEO_BRIEF} + {report_file}\n"
        )

    print(f"[OK] CEO Briefing written: {CEO_BRIEF}")
    print(f"[OK] Weekly report: {report_file}")
    print(f"   Revenue: Rs. {revenue:,.0f} | Expenses: Rs. {expenses:,.0f} | Net: Rs. {net:,.0f}")


if __name__ == "__main__":
    main()
